
export default {
    LanguageVersion: 'v1',
    LanguageTrResource: '1',
    LanguageEnResource: '2',
    Language: 'Language',
    LanguageResources: 'LanguageResources',
    MenuResources: 'MenuResources',
    CourseList: 'CourseList',
    LessonsList: 'LessonsList',
    CourseWeekList: 'CourseWeekList',
    CourseAnnouncementList: 'CourseAnnouncementList',
    AnnouncemetAllList: 'AnnouncementAllList',
    AnnouncementInboxList: 'AnnouncementInboxList',
    AnnouncementSentList:'AnnouncementSentList',
    AnnouncementDeletedList: 'AnnouncementDeletedList',
    AnnouncementDetail: 'AnnouncementDeletedList',
    DailyCalenderList: 'DailyCalenderList',
    DownloadedFilePaths:'DownloadedFilePaths',
    SavedUserName:'SavedUserName',
    SavedPassword:'SavedPassword',
    AddingActivityData:'AddingActivityData',
    MessageGroups:'MessageGroups',
    MessageDetail:'MessageDetail',
    CalenderData:'CalendarData',
    EnrollmentData:'EnrollmentData',
    UnSavedVideoTrackingData:'UnSavedVideoTrackingData',
}