# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'alms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for alms
  #pod 'Firebase/Core', '~> 6.3.0'
  #pod 'Fabric', '~> 1.10.2'
  #pod 'Crashlytics', '~> 3.13.2'
  pod 'AzureNotificationHubs-iOS'


#  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'
#
#  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
#
#  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
#
#  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  #pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  #pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  target 'almsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
